CREATE TABLE meal (
    id VARCHAR(100) NOT NULL PRIMARY KEY,
    at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    comment TEXT
);

CREATE TABLE meal_photo (
    id VARCHAR(100) NOT NULL PRIMARY KEY,
    meal_id VARCHAR(100) NOT NULL
);
