CREATE TABLE meal (
    id CHAR(36) NOT NULL PRIMARY KEY,
    at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    comment VARCHAR(1000)
);

CREATE TABLE meal_photo (
    id CHAR(36) NOT NULL PRIMARY KEY,
    meal_id CHAR(36) NOT NULL
);
